[workspace]
members = ["hal-sys"]

[package]
name = "frcrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hal-sys = { path = "hal-sys" }