[package]
name = "frc-wrap"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = "0.17.3"
frc-sys = { path = "../frc-sys" }

[build-dependencies]
pyo3 = "0.17.3"
frc-sys = { path = "../frc-sys" }