name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read rust-toolchain.toml
        id: toolchain
        shell: bash
        run: |
          TOOLCHAIN=$(cat rust-toolchain.toml | grep 'channel' | cut -d'"' -f2)
          echo "version=${TOOLCHAIN}" >> "$GITHUB_OUTPUT"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.toolchain.outputs.version }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read rust-toolchain.toml
        id: toolchain
        shell: bash
        run: |
          TOOLCHAIN=$(cat rust-toolchain.toml | grep 'channel' | cut -d'"' -f2)
          echo "version=${TOOLCHAIN}" >> "$GITHUB_OUTPUT"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.toolchain.outputs.version }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Clippy check
        run: cargo clippy --all-targets --all-features
